spring:
  datasource:
    username: root
    password: Zhzr66@$
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.255.221:3306/yzb?useUnicode=true&characterEncoding=utf-8&useSSL=false


server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml
 # config-location: classpath:config/generatorConfig.xml
